### ISSUE TITLE
Create images png/jpg

### ISSUE THREAD

**Issue by enthus1ast** [aruZeta/QRgen#21]
Printing to terminal and svg are good options already,
but sometimes it would be good to generate a png/jpg.
Maybe you could leverage pixie for this.

**Comment by aruZeta** [comment]
Yes, it's planned but haven't looked into it for the moment.

**Comment by enthus1ast** [comment]
I've written a simple pixie renderer: https://github.com/enthus1ast/QRgen/blob/pixie/tests/pixie/renderer.nim

**Comment by hamidb80** [comment]
IMO it's better to have svg, you can always convert it to a png/jpg with your favorite library/app. Like pixie/imagemagick.

Managing dependencies is not easy specially in Nim when you hit conflicts

**Comment by aruZeta** [comment]
Rendering to png/jpg should be opt in, and a benefit to directly render to it is that it will be much faster than rendering to SVG and then converting it to png/jpg.

**Comment by aruZeta** [comment]
Closed by #36
