### ISSUE TITLE
Add the ability to render to SVG

### ISSUE THREAD

**Issue by tandy-1000** [aruZeta/QRgen#8]
Could be done with Pixie maybe.

**Comment by aruZeta** [comment]
This is already listed in the [roadmap](https://github.com/users/aruZeta/projects/1/views/1) as a draft in the TODO section, I will begin working on it when I finish the current WIP issues.

**Comment by tandy-1000** [comment]
I just made the issue so I could get a notification when it is closed

**Comment by aruZeta** [comment]
Will ping you on the discord when it is, or even here on GitHub :)

**Comment by aruZeta** [comment]
Hey @tandy-1000 #10 was just finished, you can now print QR's in svg! Check [the docs](https://aruzeta.github.io/QRgen/develop/QRgen.html#printSvg%2CDrawedQRCode).
